In [1]:
import torch

In [2]:
print(torch.__version__)

2.14.0+cu126


lol the torch is on fireeeee

## GPU usage 

In [3]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

## tensors

In [4]:
scalar = torch.tensor(7)
print(scalar)
print(scalar.ndim)
print(scalar.shape)

tensor(7)
0
torch.Size([])


In [5]:
vector = torch.tensor([7, 4])
print(vector)
print(vector.ndim)
print(vector.shape)

tensor([7, 4])
1
torch.Size([2])


In [6]:
matrix = torch.tensor([[1,2],
                    [3,4]])
print(matrix)
print(matrix.ndim)
print(matrix.shape)

tensor([[1, 2],
        [3, 4]])
2
torch.Size([2, 2])


## tensors creation

In [7]:
random_tensor = torch.rand(size=(3, 3, 3))
print(random_tensor)
print(random_tensor.ndim)
print(random_tensor.shape)

tensor([[[0.7730, 0.8331, 0.1854],
         [0.6949, 0.0261, 0.0539],
         [0.2821, 0.1787, 0.9673]],

        [[0.3911, 0.4873, 0.2909],
         [0.8806, 0.8214, 0.3387],
         [0.5864, 0.8855, 0.5176]],

        [[0.8425, 0.9924, 0.5733],
         [0.2256, 0.3900, 0.0118],
         [0.6726, 0.4144, 0.7979]]])
3
torch.Size([3, 3, 3])


In [8]:
zeros = torch.zeros(size=(3,3,3))
zeros

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

In [9]:
ones = torch.ones(size=(3,3,3))
ones

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

In [10]:
# creating a tensor u dont know the shape of to match another tensor
# tensor_like = torch.ones_like(random_tensor)
# tensor_like = torch.zeros_like(random_tensor)
tensor_like = torch.rand_like(random_tensor)
tensor_like

tensor([[[0.3867, 0.4999, 0.2096],
         [0.4942, 0.2976, 0.3489],
         [0.2057, 0.1665, 0.7464]],

        [[0.2834, 0.4225, 0.9805],
         [0.4344, 0.4202, 0.7280],
         [0.7289, 0.6412, 0.4915]],

        [[0.7455, 0.2931, 0.5036],
         [0.4591, 0.0377, 0.2587],
         [0.9242, 0.7382, 0.3271]]])

## tensor manipulation

In [11]:
torch.arange(1,11,1)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
torch.mm(torch.rand(size=(3,2)), torch.rand(size=(3,2)).T)

tensor([[0.1940, 0.2123, 0.8297],
        [0.3771, 0.0924, 0.8382],
        [0.3789, 0.0893, 0.8337]])

In [13]:
torch.rand(size= (3,2)).T.shape

torch.Size([2, 3])

In [14]:
torch.mean(torch.arange(0,100,10, dtype=torch.float))

tensor(45.)

## indexing

In [15]:
x = torch.arange(1,28).reshape(3,3,3)

In [16]:
x

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]],

        [[19, 20, 21],
         [22, 23, 24],
         [25, 26, 27]]])

In [17]:
x[:, :, 2].reshape(9,1)

tensor([[ 3],
        [ 6],
        [ 9],
        [12],
        [15],
        [18],
        [21],
        [24],
        [27]])

## changing the tensor device

In [19]:
tensor_1 = torch.rand(3,3)
tensor_1.device

device(type='cpu')

In [22]:
tensor_2 = tensor_1.to(device=device)
tensor_2

tensor([[0.4493, 0.9168, 0.7854],
        [0.0054, 0.3156, 0.9990],
        [0.5023, 0.7370, 0.9849]], device='cuda:0')

In [23]:
tensor_2.to(device="cpu")

tensor([[0.4493, 0.9168, 0.7854],
        [0.0054, 0.3156, 0.9990],
        [0.5023, 0.7370, 0.9849]])